import sys
from random import randint


def guess_number(num_to_find: int, attempts: int, print_usage: bool = True):
    """
    The function allows the user to guess a random number between 1 and 99 and provides feedback on
    whether the guess is too high or too low, with the option to exit the game.

    Args:
      num_to_find (int): The random number that the user needs to guess, generated by the randint
    function from the random module.
      attempts (int): The number of attempts the user has made to guess the random number.
      print_usage (bool): A boolean parameter that determines whether or not to print the
      instructions
    for the game. If it is set to True, the instructions will be printed. If it is set to False, the
    instructions will not be printed. Defaults to True
    """
    attempts += 1
    user_input = ""
    if print_usage is True:
        print("Find the random number between 1 and 99. Type 'exit' to end the game")
    try:
        user_input = input("What's your guess between 1 and 99?\n> ")
        user_input = int(user_input)
        if int(user_input) < num_to_find:
            print("Too low!\n", end='')
        elif int(user_input) > num_to_find:
            print("Too high!\n", end='')
        else:
            if num_to_find == 42:
                print("The answer to the ultimate question of life,\
                    the universe and everything is 42.")
            if attempts == 1:
                print("First try, what a gamer!")
            else:
                print(
                    f"Congratulations, you found {num_to_find} in {attempts} attempts!")
            sys.exit()
    except ValueError:
        if user_input == 'exit':
            sys.exit("Goodbye!")
        print("That's not a number")
    guess_number(num_to_find, attempts, False)


if __name__ == "__main__":
    number_to_find = randint(1, 99)
    guess_number(number_to_find, 0)
